# Generated by Django 5.2.7 on 2025-10-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisdomquote',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wisdomquote',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
