# Generated by Django 5.2.7 on 2025-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_wisdomquote_author_alter_wisdomquote_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisdomquote',
            name='quote_text',
            field=models.TextField(default=''),
        ),
    ]
