"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, re
import boto3
import json

# Functions for working with AWS
def get_db_token(host, user, region, port=5432):
    client = boto3.client('rds')
    return client.generate_db_auth_token(
        DBHostname=host,
        Port=port,
        DBUser=user,
        Region=region
    )

def get_secret_data(secret_name, region):
    client = boto3.client('secretsmanager', region_name=region)
    secret = client.get_secret_value(SecretId=secret)
    settings = json.loads(secret['SecretString'])
    return settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-qee#r$ihc#q6jvkd^!2vr0pkzuf_-mq8@#pn*wne#ukdqshvse')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
DEPLOYMENT_TYPE = os.environ.get('DEPLOYMENT_TYPE','')

# Supported HEROKU and AWS
PLATFORM = os.environ.get('PLATFORM','')

# Assume local or staging
if DEPLOYMENT_TYPE == '':
    if PLATFORM == "HEROKU":
        # Default APP name configured by Heroku for Application created for Pull Request
        ALLOWED_HOSTS = [os.environ.get('HEROKU_APP_NAME', '') + ".herokuapp.com"]
    elif PLATFORM == "AWS":
        ALLOWED_HOSTS = [os.environ.get('DNS_NAME')]
    DB = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
elif DEPLOYMENT_TYPE == "staging":
    # User Configured variable
    if PLATFORM == "HEROKU":
        ALLOWED_HOSTS = [os.environ.get('ALLOWED_HOSTS', '')]
        DB_URL = os.environ.get('DATABASE_URL', '')
        if DB_URL:
            mobj = re.match(r'postgres://(?P<user>\w+):(?P<password>\w+)\@(?P<host>.*\.rds.amazonaws.com):(?P<port>\d+)/(?P<database>\w+)$', DB_URL)
            if mobj:
                DB = {
                    'ENGINE': 'django.db.backends.postgresql_psycopg2',
                    'NAME': mobj.group('database'),
                    'USER': mobj.group('user'),
                    'PASSWORD': mobj.group('password'),
                    'HOST': mobj.group('host'),
                    'PORT': '5432',    
                }
    # Better way to do this
    # import dj_database_url
    # DATABASES = {
    #         'default': dj_database_url.config(default='postgres://myuser:mypassword@localhost:5432/mydatabase')
    # }
    elif PLATFORM == "AWS":
        REGION = os.environ.get('AWS_REGION','us-east-1')
        SECRET_NAME = os.environ.get('SECRET_NAME','')
        settings = get_secret_data(SECRET_NAME, REGION)
        host = settings['host']
        dbname = settings['dbname']
        user = settings['username']
        port = settings['port']
        DB = {
                    'ENGINE': 'django.db.backends.postgresql_psycopg2',
                    'NAME': settings['dbname'],
                    'USER': settings['username'],
                    'PASSWORD': get_db_token(host, user, REGION, port),
                    'HOST': host,
                    'PORT': port,
                    'OPTIONS': {
                        'sslmode': 'require',
                    },
                }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quote.apps.QuoteConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': DB
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Heroky handling static files
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
